version: "3.9"

services:
  nifi:
    image: apache/nifi:2.5.0
    container_name: nifi
    hostname: nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: nifi12345678

      # Bind/advertise host+port for HTTPS
      NIFI_WEB_HTTPS_HOST: nifi
      NIFI_WEB_HTTPS_PORT: 8443

      # Use the pre-made JKS files (mounted below)
      NIFI_SECURITY_KEYSTORE: /opt/nifi/certs/keystore.jks
      NIFI_SECURITY_KEYSTORE_TYPE: JKS
      NIFI_SECURITY_KEYSTORE_PASSWD: nifi12345678
      NIFI_SECURITY_KEY_PASSWD: nifi12345678

      NIFI_SECURITY_TRUSTSTORE: /opt/nifi/certs/truststore.jks
      NIFI_SECURITY_TRUSTSTORE_TYPE: JKS
      NIFI_SECURITY_TRUSTSTORE_PASSWD: nifi12345678

      # >= 12 chars
      NIFI_SENSITIVE_PROPS_KEY: MySuperSecretKey_2025

    volumes:
      # container path with the keystore/truststore
      - ./nifi-certs/nifi:/opt/nifi/certs:ro
      - ./persist/conf:/opt/nifi/nifi-current/conf
      - nifi-logs:/opt/nifi/nifi-current/logs
      - nifi-flowfile-repo:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content-repo:/opt/nifi/nifi-current/content_repository
      - nifi-provenance-repo:/opt/nifi/nifi-current/provenance_repository
      - nifi-state:/opt/nifi/nifi-current/state
      - ./nifi-drivers:/opt/nifi/nifi-current/lib/custom

    networks:
      - airflow-nifi-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1.5G

networks:
  airflow-nifi-network:
    name: airflow-nifi-network
    external: false

volumes:
  nifi-logs:
  nifi-flowfile-repo:
  nifi-content-repo:
  nifi-provenance-repo:
  nifi-state:
