version: '3'

services:
  superset:
    init: true
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    volumes:
      - ./superset_home:/app/superset_home
    environment:
      - DATABASE_DB=superset
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
    ports:
      - '8088:8088'
  
  database:
    init: true
    image: postgres:alpine
    container_name: superset_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=secretsecret
    ports:
      - '5000:5432'